#!/usr/bin/env node
/**
 * AXI25 CLI — scaffold and wire a vault from scratch.
 *
 * Distribution modes:
 *   1) Zip: everything is already present; `wire` just (re)links the skills.
 *   2) npm / marketplace: `npx axi25 init [dir]` materializes a full,
 *      working vault (folder tree + reference files + skills), then wires it.
 *
 * Zero dependencies. Node >= 18. Creates nothing outside the target dir.
 *
 *   npx axi25 init [targetDir]   # scaffold a vault (default: ./)
 *   npx axi25 wire  [targetDir]  # (re)link skills for every harness
 *   npx axi25 --help
 */
import { promises as fs } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const HERE = path.dirname(fileURLToPath(import.meta.url));
const PKG_ROOT = path.resolve(HERE, "..");

// --- the vault skeleton (folders that must exist, each gets a .keep) ----------
const DIRS = [
  "00-capture/quick", "00-capture/diary", "00-capture/studies", "00-capture/worklogs",
  "10-sources/articles", "10-sources/books", "10-sources/courses", "10-sources/papers", "10-sources/assets",
  "20-wiki/concepts", "20-wiki/entities", "20-wiki/areas", "20-wiki/decisions",
  "20-wiki/patterns", "20-wiki/syntheses", "20-wiki/maps",
  "25-studies",
  "30-projects/active", "30-projects/someday", "30-projects/archive",
  "35-worklogs/harvest",
  "40-journal/daily", "40-journal/weekly", "40-journal/signals",
  "50-zeitgeist/discourse/articles", "50-zeitgeist/discourse/papers",
  "50-zeitgeist/discourse/threads", "50-zeitgeist/discourse/talks",
  "50-zeitgeist/syntheses", "50-zeitgeist/observations",
  "90-system/references", "90-system/prompts", "90-system/scripts",
];

// Skills are REAL directories (no symlinks — Windows-safe). `.agents/skills` is canonical
// (read natively by Codex, OpenCode, Pi). `.claude/skills` is a synced real copy for
// Claude Code + the ObsidiBot Obsidian wrapper.
const CANONICAL_SKILLS = ".agents/skills";
const CLAUDE_SKILLS = ".claude/skills";

// never copied from the package template (regenerated by wire, or noise)
const COPY_SKIP = new Set(["node_modules", ".git", ".claude"]);

// minimal anchor files written only if missing (full versions ship in the package)
const ANCHORS = {
  "index.md": `---\ntype: index\nupdated: ""\n---\n\n# Index — Wiki Catalog\n\n> The agent maintains this catalog of your \`20-wiki/\` pages. Empty for now — it fills as you build.\n`,
  "log.md": `# Operations Log\n\n> Append-only record of ingests, processing, and wiki changes. The agent writes here.\n\n<!-- entries start below this line -->\n`,
  "90-system/references/user-profile.md":
    `---\ntype: system-reference\nname: ""\nlanguage: ""\nfilename_language: match\ndate_format: ISO 8601\nset_up_on: ""\nworks_with_media: false\n---\n\n<!-- ONBOARDING PENDING -->\n<!--\n  This vault has not been set up. While this marker is present, run the\n  \`axi25-onboarding\` skill first. Onboarding fills this file and removes the marker.\n-->\n\n# User Profile\n\n> Every skill reads this file for your name, language, and areas. Onboarding writes it.\n`,
};

const log = (m) => process.stdout.write(`  ${m}\n`);
const ok = (m) => log(`\x1b[32m✓\x1b[0m ${m}`);
const warn = (m) => log(`\x1b[33m!\x1b[0m ${m}`);

async function exists(p) { try { await fs.lstat(p); return true; } catch { return false; } }

async function copyTree(src, dst) {
  const entries = await fs.readdir(src, { withFileTypes: true });
  for (const e of entries) {
    if (COPY_SKIP.has(e.name)) continue;
    const s = path.join(src, e.name);
    const d = path.join(dst, e.name);
    if (e.isDirectory()) {
      await fs.mkdir(d, { recursive: true });
      await copyTree(s, d);
    } else if (e.isSymbolicLink()) {
      // skip symlinks from the template; `wire` recreates the ones we need
    } else if (!(await exists(d))) {
      await fs.copyFile(s, d);
    }
  }
}

async function ensureSkeleton(root) {
  for (const dir of DIRS) {
    const abs = path.join(root, dir);
    await fs.mkdir(abs, { recursive: true });
    const keep = path.join(abs, ".keep");
    if (!(await exists(keep))) await fs.writeFile(keep, "");
  }
  for (const [rel, content] of Object.entries(ANCHORS)) {
    const abs = path.join(root, rel);
    await fs.mkdir(path.dirname(abs), { recursive: true });
    if (!(await exists(abs))) await fs.writeFile(abs, content);
  }
}

async function wireSkills(root) {
  const canonical = path.join(root, CANONICAL_SKILLS);
  if (!(await exists(canonical))) {
    warn(".agents/skills not found — skills unavailable. Reinstall or run `init` from the package.");
    return;
  }
  ok(".agents/skills — canonical (Codex, OpenCode, Pi read this natively)");
  // Sync .claude/skills as a REAL copy (no symlinks → works on any OS, any extractor).
  const claudeSkills = path.join(root, CLAUDE_SKILLS);
  await fs.rm(claudeSkills, { recursive: true, force: true });
  await fs.mkdir(path.dirname(claudeSkills), { recursive: true });
  await fs.cp(canonical, claudeSkills, { recursive: true });
  ok(".claude/skills — real copy for Claude Code + the ObsidiBot Obsidian wrapper");
}

async function cmdInit(dir) {
  const root = path.resolve(dir || ".");
  await fs.mkdir(root, { recursive: true });
  log("");
  log(`AXI25 — scaffolding into ${root}`);
  log("=".repeat(28));
  if (path.resolve(PKG_ROOT) !== root) {
    // materialize the packaged template (full product) into the target
    await copyTree(PKG_ROOT, root);
    ok("Vault template copied");
  }
  await ensureSkeleton(root);
  ok("Folder tree + anchor files ready");
  await wireSkills(root);
  log("");
  ok("Done. Open the folder in your AI agent (Claude Code / Codex / OpenCode / Pi) and type: onboarding");
  log("");
}

async function cmdWire(dir) {
  const root = path.resolve(dir || ".");
  log("");
  await ensureSkeleton(root);
  await wireSkills(root);
  ok("Wired.");
  log("");
}

// Cross-platform: is an executable on PATH? (no shell-out, zero deps)
async function onPath(name) {
  const dirs = (process.env.PATH || "").split(path.delimiter).filter(Boolean);
  const exts = process.platform === "win32"
    ? (process.env.PATHEXT || ".EXE;.CMD;.BAT").split(";")
    : [""];
  for (const d of dirs) {
    for (const ext of exts) {
      if (await exists(path.join(d, name + ext))) return true;
      if (await exists(path.join(d, name + ext.toLowerCase()))) return true;
    }
  }
  return false;
}

// The facilitated command for power users: check the environment, say the exact next step.
async function cmdDoctor(dir) {
  const root = path.resolve(dir || ".");
  log("");
  log("AXI25 — environment check");
  log("=".repeat(28));

  const has = {};
  for (const c of ["claude", "codex", "opencode", "pi", "node", "git"]) has[c] = await onPath(c);
  const mark = (b) => (b ? "\x1b[32m✓\x1b[0m" : "\x1b[33m—\x1b[0m");
  for (const c of ["claude", "codex", "opencode", "pi", "node", "git"]) log(`${mark(has[c])} ${c}`);

  const agents = ["claude", "codex", "opencode", "pi"].filter((a) => has[a]);
  log("");
  if (agents.length) {
    ok(`Ready. Open this folder with: ${agents[0]}   then type:  onboarding`);
    if (agents.length > 1) log(`(also available: ${agents.slice(1).join(", ")})`);
  } else {
    warn("No AI agent CLI found on PATH.");
    log("Pick one and install it, then re-run `npx axi25 doctor`:");
    log("  • Claude Code : npm i -g @anthropic-ai/claude-code   (Pro/Max login)");
    log("  • OpenAI Codex: npm i -g @openai/codex");
    log("  • OpenCode    : https://opencode.ai   • Pi: https://pi.dev");
    if (!has.node) log("  (Node.js first: https://nodejs.org — needed for the npm installs.)");
    log("Or open the vault in any agent and say \"check my setup\" — axi25-doctor installs it for you.");
  }
  if (!has.git) log("Tip: install git for automatic backup/version history of your vault.");
  log("");
}

function help() {
  process.stdout.write(`
AXI25 — CLI

  npx axi25 doctor [dir]  Check your environment and print the exact next step
  npx axi25 init [dir]    Scaffold a full vault from scratch (default: current folder)
  npx axi25 wire [dir]    Re-sync the .claude/skills copy + ensure the folder tree
  npx axi25 --help        This help

Lay users: just open the folder in Obsidian (see SETUP.md) — no command needed.
Power users: run \`doctor\`, then open the folder in your agent and type:  onboarding
`);
}

const [cmd, arg] = process.argv.slice(2);
try {
  if (cmd === "init") await cmdInit(arg);
  else if (cmd === "wire") await cmdWire(arg);
  else if (cmd === "doctor" || cmd === "check") await cmdDoctor(arg);
  else help();
} catch (err) {
  process.stderr.write(`\n  Error: ${err.message}\n`);
  process.exit(1);
}
